[package]
name = "vape421_lunar_dump"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "Vape421LunarDump"
crate-type = ["cdylib", "rlib"]

[dependencies]
vape421_core = { path = "../vape421_core" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
