package gg.vape.mapping;

import gg.vape.Vape;
import gg.vape.mapping.MappedClasses;
import gg.vape.mapping.Mapping;
import gg.vape.mapping.mappings.MAbstractBlockProperties;
import gg.vape.mapping.mappings.MAbstractBlockState;
import gg.vape.mapping.mappings.MAbstractClientPlayer;
import gg.vape.mapping.mappings.MAbstractClientPlayerBridge;
import gg.vape.mapping.mappings.MAbstractGui;
import gg.vape.mapping.mappings.MActiveRenderInfo;
import gg.vape.mapping.mappings.MArmorMaterial;
import gg.vape.mapping.mappings.MAtomicReferenceArrayBridge;
import gg.vape.mapping.mappings.MAttributeModifier;
import gg.vape.mapping.mappings.MAxisAlignedBB;
import gg.vape.mapping.mappings.MBiome;
import gg.vape.mapping.mappings.MBiomeProviderBridge;
import gg.vape.mapping.mappings.MBiomeRegistryName;
import gg.vape.mapping.mappings.MBiomeRegistrySwitch;
import gg.vape.mapping.mappings.MBlock;
import gg.vape.mapping.mappings.MBlockBed;
import gg.vape.mapping.mappings.MBlockHorizontal;
import gg.vape.mapping.mappings.MBlockLayerOverrideFallbackHook;
import gg.vape.mapping.mappings.MBlockModelRenderer;
import gg.vape.mapping.mappings.MBlockPos;
import gg.vape.mapping.mappings.MBlockPosCarrier;
import gg.vape.mapping.mappings.MBlockRayTraceResult;
import gg.vape.mapping.mappings.MBlockReader;
import gg.vape.mapping.mappings.MBlockReaderBridge;
import gg.vape.mapping.mappings.MBlockStateBridge;
import gg.vape.mapping.mappings.MBlockStateContainerBridge;
import gg.vape.mapping.mappings.MBlockStateWorldBridge;
import gg.vape.mapping.mappings.MBlocks;
import gg.vape.mapping.mappings.MBuiltInRegistries;
import gg.vape.mapping.mappings.MBytePacketFieldBridge;
import gg.vape.mapping.mappings.MC03PacketPlayerBridge;
import gg.vape.mapping.mappings.MC0BPacketEntityAction_Action;
import gg.vape.mapping.mappings.MCPacketAnimation;
import gg.vape.mapping.mappings.MCPacketChatMessage;
import gg.vape.mapping.mappings.MCPacketEntityAction;
import gg.vape.mapping.mappings.MCPacketHeldItemChange;
import gg.vape.mapping.mappings.MCPacketPlayer;
import gg.vape.mapping.mappings.MCPacketPlayerBlockPlacement;
import gg.vape.mapping.mappings.MCPacketPlayerDigging;
import gg.vape.mapping.mappings.MCPacketPlayer_Position;
import gg.vape.mapping.mappings.MCPacketPlayer_PositionRotation;
import gg.vape.mapping.mappings.MCPacketPlayer_Rotation;
import gg.vape.mapping.mappings.MCPacketUseEntity;
import gg.vape.mapping.mappings.MCPacketUseEntityAction;
import gg.vape.mapping.mappings.MCPacketUseEntityActionPacket;
import gg.vape.mapping.mappings.MCPacketUseEntityOne;
import gg.vape.mapping.mappings.MCPacketUseEntityPacket;
import gg.vape.mapping.mappings.MCaughtEntityActionBridge;
import gg.vape.mapping.mappings.MChannel;
import gg.vape.mapping.mappings.MChatMessageRenderTarget;
import gg.vape.mapping.mappings.MChestType;
import gg.vape.mapping.mappings.MChestTypeHolder;
import gg.vape.mapping.mappings.MChunk;
import gg.vape.mapping.mappings.MChunkSection;
import gg.vape.mapping.mappings.MClickType;
import gg.vape.mapping.mappings.MClientChatReceivedEvent;
import gg.vape.mapping.mappings.MClientChunkProvider;
import gg.vape.mapping.mappings.MContainer;
import gg.vape.mapping.mappings.MDamageSource;
import gg.vape.mapping.mappings.MDamageSources;
import gg.vape.mapping.mappings.MDataComponentMap;
import gg.vape.mapping.mappings.MDataComponents;
import gg.vape.mapping.mappings.MDefaultVertexFormats;
import gg.vape.mapping.mappings.MDeltaTracker;
import gg.vape.mapping.mappings.MDirection;
import gg.vape.mapping.mappings.MDirectionAxis;
import gg.vape.mapping.mappings.MDirectionBridge;
import gg.vape.mapping.mappings.MDirectionVector;
import gg.vape.mapping.mappings.MEffectRenderer;
import gg.vape.mapping.mappings.MEmptyDataComponentMap;
import gg.vape.mapping.mappings.MEmptyItemAttributeModifiers;
import gg.vape.mapping.mappings.MEnchantment;
import gg.vape.mapping.mappings.MEnchantmentHelper;
import gg.vape.mapping.mappings.MEnchantmentHelperBridge;
import gg.vape.mapping.mappings.MEnchantmentModifierDamage;
import gg.vape.mapping.mappings.MEnchantments;
import gg.vape.mapping.mappings.MEnderPearlProjectileBridge;
import gg.vape.mapping.mappings.MEntity;
import gg.vape.mapping.mappings.MEntityArrow;
import gg.vape.mapping.mappings.MEntityClientPlayerMP;
import gg.vape.mapping.mappings.MEntityEnderPearl;
import gg.vape.mapping.mappings.MEntityEquipmentSlot;
import gg.vape.mapping.mappings.MEntityEquipmentSlotHolder;
import gg.vape.mapping.mappings.MEntityFX;
import gg.vape.mapping.mappings.MEntityFishHook;
import gg.vape.mapping.mappings.MEntityItem;
import gg.vape.mapping.mappings.MEntityLiving;
import gg.vape.mapping.mappings.MEntityLivingBase;
import gg.vape.mapping.mappings.MEntityOtherPlayerMP;
import gg.vape.mapping.mappings.MEntityPlayer;
import gg.vape.mapping.mappings.MEntityPlayerMacroBridge;
import gg.vape.mapping.mappings.MEntityPlayerSP;
import gg.vape.mapping.mappings.MEntityPotion;
import gg.vape.mapping.mappings.MEntityRayTraceBridge;
import gg.vape.mapping.mappings.MEntityRayTraceResult;
import gg.vape.mapping.mappings.MEntityRemovalReason;
import gg.vape.mapping.mappings.MEntityRenderer;
import gg.vape.mapping.mappings.MEntityRendererFogDensityHook;
import gg.vape.mapping.mappings.MEntitySelectors;
import gg.vape.mapping.mappings.MEntitySize;
import gg.vape.mapping.mappings.MEnumActionResult;
import gg.vape.mapping.mappings.MEnumCreatureAttribute;
import gg.vape.mapping.mappings.MEnumCreatureAttributeBridge;
import gg.vape.mapping.mappings.MEnumFacing;
import gg.vape.mapping.mappings.MEnumHand;
import gg.vape.mapping.mappings.MEnumHandBridge;
import gg.vape.mapping.mappings.MEnumParticleTypes;
import gg.vape.mapping.mappings.MEnumWorldBlockLayer;
import gg.vape.mapping.mappings.MEquipmentSlotSet;
import gg.vape.mapping.mappings.MEquippable;
import gg.vape.mapping.mappings.MEvent;
import gg.vape.mapping.mappings.MFluidState;
import gg.vape.mapping.mappings.MFontGlyph;
import gg.vape.mapping.mappings.MFontGlyphInfo;
import gg.vape.mapping.mappings.MFontManager;
import gg.vape.mapping.mappings.MFontRenderer;
import gg.vape.mapping.mappings.MFontSet;
import gg.vape.mapping.mappings.MFoodProperties;
import gg.vape.mapping.mappings.MFoodStats;
import gg.vape.mapping.mappings.MFoods;
import gg.vape.mapping.mappings.MFramebuffer;
import gg.vape.mapping.mappings.MFreecamMovementInputBridge;
import gg.vape.mapping.mappings.MFreecamPlayerBridge;
import gg.vape.mapping.mappings.MGL11;
import gg.vape.mapping.mappings.MGL20;
import gg.vape.mapping.mappings.MGameProfile;
import gg.vape.mapping.mappings.MGameSettings;
import gg.vape.mapping.mappings.MGameSettingsGuiScale;
import gg.vape.mapping.mappings.MGameSettingsGuiScaleValue;
import gg.vape.mapping.mappings.MGameSettingsValue;
import gg.vape.mapping.mappings.MGlStateManager;
import gg.vape.mapping.mappings.MGlStateManagerFogStateBridge;
import gg.vape.mapping.mappings.MGlStateManagerFogStateObject;
import gg.vape.mapping.mappings.MGlStateManagerTexGenCoord;
import gg.vape.mapping.mappings.MGlStateManagerTexGenState;
import gg.vape.mapping.mappings.MGlStateManager_BlendState;
import gg.vape.mapping.mappings.MGlStateManager_FogState;
import gg.vape.mapping.mappings.MGlStateManager_TextureState;
import gg.vape.mapping.mappings.MGlyphInfo;
import gg.vape.mapping.mappings.MGlyphProvider;
import gg.vape.mapping.mappings.MGuiChat;
import gg.vape.mapping.mappings.MGuiChest;
import gg.vape.mapping.mappings.MGuiContainer;
import gg.vape.mapping.mappings.MGuiContainerCreativeSlot;
import gg.vape.mapping.mappings.MGuiInventory;
import gg.vape.mapping.mappings.MGuiPlayerTabOverlay;
import gg.vape.mapping.mappings.MGuiScreen;
import gg.vape.mapping.mappings.MGuiSpriteManager;
import gg.vape.mapping.mappings.MHolder;
import gg.vape.mapping.mappings.MI18n;
import gg.vape.mapping.mappings.MIAttributeInstance;
import gg.vape.mapping.mappings.MIBlockState;
import gg.vape.mapping.mappings.MIChunkProvider;
import gg.vape.mapping.mappings.MIInventory;
import gg.vape.mapping.mappings.MISelectionContext;
import gg.vape.mapping.mappings.MITextComponent;
import gg.vape.mapping.mappings.MITooltipFlag;
import gg.vape.mapping.mappings.MITooltipFlagBridge;
import gg.vape.mapping.mappings.MIWorldNameable;
import gg.vape.mapping.mappings.MInputMappings;
import gg.vape.mapping.mappings.MInputMappingsBridge;
import gg.vape.mapping.mappings.MInputMappingsInput;
import gg.vape.mapping.mappings.MInventoryListBridge;
import gg.vape.mapping.mappings.MInventoryPlayer;
import gg.vape.mapping.mappings.MItem;
import gg.vape.mapping.mappings.MItemActionResult;
import gg.vape.mapping.mappings.MItemArmor;
import gg.vape.mapping.mappings.MItemAttributeModifiers;
import gg.vape.mapping.mappings.MItemAttributeModifiersComponent;
import gg.vape.mapping.mappings.MItemAttributeModifiersComponent$Entry;
import gg.vape.mapping.mappings.MItemBlock;
import gg.vape.mapping.mappings.MItemBlockBridge;
import gg.vape.mapping.mappings.MItemCameraTransformBaseBridge;
import gg.vape.mapping.mappings.MItemCameraTransformIntermediateBridge;
import gg.vape.mapping.mappings.MItemCameraTransformLeafBridge;
import gg.vape.mapping.mappings.MItemCameraTransformType;
import gg.vape.mapping.mappings.MItemPotion;
import gg.vape.mapping.mappings.MItemRenderContext;
import gg.vape.mapping.mappings.MItemRenderer;
import gg.vape.mapping.mappings.MItemRendererBridge;
import gg.vape.mapping.mappings.MItemStack;
import gg.vape.mapping.mappings.MItemSword;
import gg.vape.mapping.mappings.MItemTool;
import gg.vape.mapping.mappings.MItem_ToolMaterial;
import gg.vape.mapping.mappings.MItems;
import gg.vape.mapping.mappings.MKeyBinding;
import gg.vape.mapping.mappings.MKeyboardHandler;
import gg.vape.mapping.mappings.MLanguage;
import gg.vape.mapping.mappings.MLanguageStateBridge;
import gg.vape.mapping.mappings.MLaunchClassLoader;
import gg.vape.mapping.mappings.MLegacyEntityRenderPreHook;
import gg.vape.mapping.mappings.MLightTexture;
import gg.vape.mapping.mappings.MLists;
import gg.vape.mapping.mappings.MMLGBlockWrapper;
import gg.vape.mapping.mappings.MMainWindow;
import gg.vape.mapping.mappings.MMappedClassSlotFp;
import gg.vape.mapping.mappings.MMappedClassSlotNRegistration;
import gg.vape.mapping.mappings.MMappedClassSlotZG;
import gg.vape.mapping.mappings.MMappedFieldSingletonWrapper;
import gg.vape.mapping.mappings.MMaterial;
import gg.vape.mapping.mappings.MMatrix4f;
import gg.vape.mapping.mappings.MMatrix4fHandle;
import gg.vape.mapping.mappings.MMatrix4fTransformVariantBridge;
import gg.vape.mapping.mappings.MMatrixStack;
import gg.vape.mapping.mappings.MMatrixStackEntry;
import gg.vape.mapping.mappings.MMethodSlotZYBridge;
import gg.vape.mapping.mappings.MMinecraft;
import gg.vape.mapping.mappings.MMinecraftBridge;
import gg.vape.mapping.mappings.MMobSpawnerBaseLogic;
import gg.vape.mapping.mappings.MModelBiped;
import gg.vape.mapping.mappings.MModelManager;
import gg.vape.mapping.mappings.MModelPlayer;
import gg.vape.mapping.mappings.MModelRenderer;
import gg.vape.mapping.mappings.MMouseEvent;
import gg.vape.mapping.mappings.MMouseHelper;
import gg.vape.mapping.mappings.MMovementInput;
import gg.vape.mapping.mappings.MMoverType;
import gg.vape.mapping.mappings.MMutableBoundingBox;
import gg.vape.mapping.mappings.MMutableTextComponent;
import gg.vape.mapping.mappings.MNBTTagCompound;
import gg.vape.mapping.mappings.MNBTTagList;
import gg.vape.mapping.mappings.MNetHandlerPlayClient;
import gg.vape.mapping.mappings.MNetHandlerPlayClientImpl;
import gg.vape.mapping.mappings.MNetworkManager;
import gg.vape.mapping.mappings.MNetworkManager_InboundHandlerTuplePacketListener;
import gg.vape.mapping.mappings.MNetworkPlayerInfo;
import gg.vape.mapping.mappings.MNonNullList;
import gg.vape.mapping.mappings.MOpenedChestTypeSentinelBridge;
import gg.vape.mapping.mappings.MOrdering;
import gg.vape.mapping.mappings.MPacket;
import gg.vape.mapping.mappings.MPacketIdFactory;
import gg.vape.mapping.mappings.MPacketVelocityBridge;
import gg.vape.mapping.mappings.MPlaySoundAtEntityEvent;
import gg.vape.mapping.mappings.MPlayerControllerMP;
import gg.vape.mapping.mappings.MPlayerDiggingAction;
import gg.vape.mapping.mappings.MPlayerEvent_NameFormat;
import gg.vape.mapping.mappings.MPlayerInfo;
import gg.vape.mapping.mappings.MPlayerInput;
import gg.vape.mapping.mappings.MPlayerInteractEvent;
import gg.vape.mapping.mappings.MPlayerModel;
import gg.vape.mapping.mappings.MPlayerSkin;
import gg.vape.mapping.mappings.MPointOfView;
import gg.vape.mapping.mappings.MPositionMoveRotation;
import gg.vape.mapping.mappings.MPotion;
import gg.vape.mapping.mappings.MPotionEffect;
import gg.vape.mapping.mappings.MPotionVersionRange;
import gg.vape.mapping.mappings.MQuaternion;
import gg.vape.mapping.mappings.MRayTraceContext;
import gg.vape.mapping.mappings.MRayTraceContext_BlockMode;
import gg.vape.mapping.mappings.MRayTraceContext_FluidMode;
import gg.vape.mapping.mappings.MRayTraceResult;
import gg.vape.mapping.mappings.MRayTraceResult_Type;
import gg.vape.mapping.mappings.MRegistry;
import gg.vape.mapping.mappings.MRegistryAccess;
import gg.vape.mapping.mappings.MRegistryAccessBridge;
import gg.vape.mapping.mappings.MRegistryLookup;
import gg.vape.mapping.mappings.MRegistryNamespaced;
import gg.vape.mapping.mappings.MRegistrySimple;
import gg.vape.mapping.mappings.MRegistryValueBridge;
import gg.vape.mapping.mappings.MRender;
import gg.vape.mapping.mappings.MRenderBatchFlushTarget;
import gg.vape.mapping.mappings.MRenderBlocks;
import gg.vape.mapping.mappings.MRenderBufferBridge;
import gg.vape.mapping.mappings.MRenderGameOverlayEvent;
import gg.vape.mapping.mappings.MRenderGlobal;
import gg.vape.mapping.mappings.MRenderHelper;
import gg.vape.mapping.mappings.MRenderItem;
import gg.vape.mapping.mappings.MRenderItemContext;
import gg.vape.mapping.mappings.MRenderLivingBase;
import gg.vape.mapping.mappings.MRenderManager;
import gg.vape.mapping.mappings.MRenderPlayer;
import gg.vape.mapping.mappings.MRenderStateBridge;
import gg.vape.mapping.mappings.MRenderStateBridgeVariant;
import gg.vape.mapping.mappings.MRenderStateBuilder;
import gg.vape.mapping.mappings.MRenderSystem;
import gg.vape.mapping.mappings.MRenderTypeBuffer;
import gg.vape.mapping.mappings.MRenderTypeBufferBridge;
import gg.vape.mapping.mappings.MRenderWorldLastEvent;
import gg.vape.mapping.mappings.MResourceKey;
import gg.vape.mapping.mappings.MResourceKeyEnchantmentBridge;
import gg.vape.mapping.mappings.MResourceKeyHolder;
import gg.vape.mapping.mappings.MResourceKeyRegistryLookup;
import gg.vape.mapping.mappings.MResourceKeyRegistryLookupStreamBridge;
import gg.vape.mapping.mappings.MResourceLocation;
import gg.vape.mapping.mappings.MResourceLocationConstantsBridge;
import gg.vape.mapping.mappings.MResourceLocationKey;
import gg.vape.mapping.mappings.MResourceLocationName;
import gg.vape.mapping.mappings.MResourceManager;
import gg.vape.mapping.mappings.MS08PacketPlayerPosLook;
import gg.vape.mapping.mappings.MSEntityPacket;
import gg.vape.mapping.mappings.MSPacketAnimation;
import gg.vape.mapping.mappings.MSPacketBlockChange;
import gg.vape.mapping.mappings.MSPacketChunkData;
import gg.vape.mapping.mappings.MSPacketChunkDataExtracted;
import gg.vape.mapping.mappings.MSPacketDestroyEntities;
import gg.vape.mapping.mappings.MSPacketDestroyEntitiesArrayBridge;
import gg.vape.mapping.mappings.MSPacketEntity;
import gg.vape.mapping.mappings.MSPacketEntityStatus;
import gg.vape.mapping.mappings.MSPacketEntityTeleport;
import gg.vape.mapping.mappings.MSPacketEntityVelocity;
import gg.vape.mapping.mappings.MSPacketExplosion;
import gg.vape.mapping.mappings.MSPacketHeldItemChange;
import gg.vape.mapping.mappings.MSPacketMapChunkBulk;
import gg.vape.mapping.mappings.MSPacketMapChunkBulkBridge;
import gg.vape.mapping.mappings.MSPacketPlayerPosLook;
import gg.vape.mapping.mappings.MSPacketSoundEffect;
import gg.vape.mapping.mappings.MSPacketSoundEffectBridge;
import gg.vape.mapping.mappings.MScore;
import gg.vape.mapping.mappings.MScoreObjective;
import gg.vape.mapping.mappings.MScorePlayerTeam;
import gg.vape.mapping.mappings.MScoreboard;
import gg.vape.mapping.mappings.MScreen;
import gg.vape.mapping.mappings.MServerData;
import gg.vape.mapping.mappings.MSession;
import gg.vape.mapping.mappings.MSetVisibility;
import gg.vape.mapping.mappings.MShaderGroup;
import gg.vape.mapping.mappings.MSharedMonsterAttributes;
import gg.vape.mapping.mappings.MSharedMonsterAttributesBridge;
import gg.vape.mapping.mappings.MSharedMonsterAttributesVariantBridge;
import gg.vape.mapping.mappings.MShortPacketFieldBridge;
import gg.vape.mapping.mappings.MSlot;
import gg.vape.mapping.mappings.MSoundAwareEntityFX;
import gg.vape.mapping.mappings.MSoundEvent;
import gg.vape.mapping.mappings.MSoundEventRegistryName;
import gg.vape.mapping.mappings.MStatusEffect;
import gg.vape.mapping.mappings.MStatusEffectSpriteUploader;
import gg.vape.mapping.mappings.MStringTextComponent;
import gg.vape.mapping.mappings.MStringTextComponentBridge;
import gg.vape.mapping.mappings.MStyle;
import gg.vape.mapping.mappings.MTeam;
import gg.vape.mapping.mappings.MTessellator;
import gg.vape.mapping.mappings.MTextComponent;
import gg.vape.mapping.mappings.MTextComponentBaseBridge;
import gg.vape.mapping.mappings.MTextComponentString;
import gg.vape.mapping.mappings.MTextComponentTranslation;
import gg.vape.mapping.mappings.MTextComponentTranslationBridge;
import gg.vape.mapping.mappings.MTextFormatting;
import gg.vape.mapping.mappings.MTextureAtlasSprite;
import gg.vape.mapping.mappings.MTextureAtlasSpriteInfo;
import gg.vape.mapping.mappings.MTextureAtlasSpriteInfoBridge;
import gg.vape.mapping.mappings.MTextureManager;
import gg.vape.mapping.mappings.MTextureManagerHandle;
import gg.vape.mapping.mappings.MTextureObject;
import gg.vape.mapping.mappings.MTextureObjectHandle;
import gg.vape.mapping.mappings.MTickEventPhase;
import gg.vape.mapping.mappings.MTickEvent_Phase;
import gg.vape.mapping.mappings.MTileEntity;
import gg.vape.mapping.mappings.MTileEntityChest;
import gg.vape.mapping.mappings.MTileEntityEnderChest;
import gg.vape.mapping.mappings.MTileEntityMobSpawner;
import gg.vape.mapping.mappings.MTimer;
import gg.vape.mapping.mappings.MTitledScreen;
import gg.vape.mapping.mappings.MTrajectoriesItemBridge;
import gg.vape.mapping.mappings.MUtil;
import gg.vape.mapping.mappings.MVec3I;
import gg.vape.mapping.mappings.MVec3d;
import gg.vape.mapping.mappings.MVector3f;
import gg.vape.mapping.mappings.MVertexFormatElement;
import gg.vape.mapping.mappings.MVisGraph;
import gg.vape.mapping.mappings.MVoxelShape;
import gg.vape.mapping.mappings.MVoxelShapeBridge;
import gg.vape.mapping.mappings.MWorld;
import gg.vape.mapping.mappings.MWorldClient;
import gg.vape.mapping.mappings.MWorldClientBridge;
import gg.vape.mapping.mappings.MWorldCollisionConsumerBridge;
import gg.vape.mapping.mappings.MWorldInfo;
import gg.vape.mapping.mappings.MWorldRenderer;
import gg.vape.mapping.mappings.MWorldRendererBuilder;
import gg.vape.runtime.ObfuscatedRuntimeException;
import gg.vape.ui.click.component.GuiComponent;
import gg.vape.utils.render.GuiRenderPrimitives;
import gg.vape.wrapper.impl.ForgeVersion;
import java.util.ArrayList;
import java.util.List;

public class Mapper {
    public MDirectionAxis p;
    public MResourceKeyRegistryLookupStreamBridge R2;
    public MWorldRenderer qZ;
    public MTextureManagerHandle hL;
    public MTickEventPhase R8;
    public MGuiContainerCreativeSlot Db;
    public MBlockModelRenderer hE;
    public MEntityEquipmentSlot CY;
    public MRayTraceContext_FluidMode DG;
    public MSPacketPlayerPosLook Ry;
    public MDataComponentMap qk;
    public MCPacketHeldItemChange Ck;
    public MGuiChest Ch;
    private static int DH;
    public MMouseHelper qI;
    public MBlockStateWorldBridge hu;
    public MWorld Cy;
    public MPlayerControllerMP hj;
    public MLists hY;
    public MEntityEquipmentSlotHolder hh;
    public MGlStateManager_BlendState qG;
    public MBlockBed Dj;
    public MWorldClient ha;
    public MEntityRemovalReason h;
    public MRenderItemContext A;
    public MGlStateManager Dt;
    public MPacketVelocityBridge qO;
    public MCPacketPlayerBlockPlacement D3;
    public MBlocks Rd;
    public MFontRenderer R7;
    public MFreecamPlayerBridge w;
    public MInputMappings CW;
    public MVoxelShape Cr;
    public MMLGBlockWrapper Rj;
    public MCPacketPlayer_PositionRotation qq;
    public MEnchantmentHelperBridge q4;
    public MTileEntityChest hI;
    public MBiomeProviderBridge K;
    public MGL11 k;
    public MFontSet Z;
    public MItemCameraTransformType qu;
    public MDamageSource RK;
    public MEntity Rr;
    public MMatrix4fTransformVariantBridge Rq;
    public MGlStateManager_FogState D2;
    public MBlockReaderBridge y;
    public MTextureAtlasSpriteInfo R6;
    public MFoods hT;
    public MCPacketChatMessage RN;
    public MMappedClassSlotFp m;
    public MEnchantment RC;
    public MUtil Rf;
    public MItemCameraTransformBaseBridge hc;
    public MPlayerInput RI;
    public MTitledScreen ql;
    public MCPacketPlayer_Position R5;
    public MItemAttributeModifiersComponent$Entry DN;
    public MEntityEnderPearl Dl;
    public MInputMappingsBridge CE;
    public MVertexFormatElement Dc;
    public MGlStateManagerTexGenState hs;
    public MTextComponentBaseBridge Cp;
    public MWorldInfo Dw;
    public MActiveRenderInfo hi;
    public MCPacketPlayer_Rotation Cv;
    public MTickEvent_Phase hz;
    public MInventoryPlayer v;
    public MMoverType q6;
    public MAbstractBlockProperties CQ;
    public MResourceLocationKey qK;
    public MEmptyDataComponentMap RS;
    public MCPacketUseEntityAction qz;
    public MChestTypeHolder L;
    public MMainWindow DU;
    public MEntityRayTraceResult qS;
    public MScore Cm;
    public MPotion qU;
    public MItemPotion CI;
    public MEntityLiving W;
    public MAbstractClientPlayerBridge Dk;
    public MItemAttributeModifiers Cd;
    public MMatrix4fHandle D8;
    public MModelPlayer Ri;
    public MFontGlyphInfo hZ;
    public MSoundEvent Cb;
    public MRenderGlobal Df;
    public MBuiltInRegistries q7;
    public MItems Rl;
    public MRegistryLookup DO;
    public MDeltaTracker RU;
    public MGlStateManagerFogStateObject R;
    public MRegistryAccess qs;
    public MRenderBatchFlushTarget hX;
    public MRenderBufferBridge Ca;
    public MVec3I Dn;
    public MMatrixStack qn;
    public MCPacketUseEntityActionPacket h6;
    public MWorldClientBridge q0;
    public MPlayerEvent_NameFormat R1;
    public MGL20 RW;
    public MMinecraftBridge D9;
    public MBiome Rm;
    public MPacketIdFactory hp;
    public MEntityRendererFogDensityHook V;
    public MC0BPacketEntityAction_Action DQ;
    public MEntityOtherPlayerMP h_;
    public MSPacketAnimation DF;
    public MCaughtEntityActionBridge hC;
    public MEnderPearlProjectileBridge CH;
    public MSharedMonsterAttributesBridge h3;
    public MPlayerInfo CG;
    public MStatusEffect Rb;
    public MNBTTagList I;
    public MEnumWorldBlockLayer hA;
    public MEmptyItemAttributeModifiers Rw;
    public MIAttributeInstance Rv;
    public MEntityClientPlayerMP q_;
    public MCPacketUseEntityOne RE;
    public MGameSettingsValue DM;
    public MEnumFacing O;
    public MRegistryNamespaced qc;
    public MMovementInput h7;
    public MLightTexture hF;
    public MGuiPlayerTabOverlay hP;
    public MWorldRendererBuilder D;
    public MGameProfile d;
    public MEnchantmentModifierDamage t;
    public MKeyboardHandler CR;
    public MFontManager qb;
    public MGlStateManager_TextureState hH;
    public MResourceManager C2;
    public MEnchantmentHelper Rk;
    public MSPacketSoundEffect Cs;
    public MCPacketUseEntityPacket Co;
    public MSPacketMapChunkBulkBridge Rg;
    public MSPacketBlockChange CN;
    public MRenderTypeBuffer c;
    public MChestType qa;
    public MRayTraceContext_BlockMode R3;
    public MDirectionBridge D5;
    public MIWorldNameable Dm;
    public MItemAttributeModifiersComponent r;
    public MIBlockState DE;
    public MMutableTextComponent RJ;
    public MResourceLocationName qt;
    public MITooltipFlagBridge qh;
    public MTeam qW;
    public MChatMessageRenderTarget qd;
    public MScoreObjective qL;
    public MModelBiped Ct;
    public MTextureObject hG;
    public MStringTextComponentBridge DK;
    public MModelManager CZ;
    public MTileEntityEnderChest D4;
    public MPlayerModel Rc;
    public MEnumHandBridge hR;
    public MOrdering qm;
    public MRenderGameOverlayEvent h5;
    public MSharedMonsterAttributes qr;
    public MPlaySoundAtEntityEvent C5;
    public MBlockStateContainerBridge Ds;
    public MAbstractClientPlayer Du;
    public MSPacketEntityStatus RO;
    public MBlockReader DV;
    public MDirection Q;
    public MNonNullList DR;
    public MQuaternion qf;
    public MSlot qY;
    public MResourceLocation C9;
    public MMaterial Cn;
    public MIInventory X;
    public MFontGlyph De;
    public MGuiContainer hK;
    public MSPacketEntity qR;
    public MScorePlayerTeam Rh;
    public MCPacketUseEntity Ra;
    public MEntityPlayerSP CC;
    public MShaderGroup Qv;
    public MTimer hr;
    public MMatrix4f qJ;
    public MInputMappingsInput hm;
    public MAbstractGui qQ;
    public MEvent qv;
    public MTrajectoriesItemBridge RX;
    public MItemRenderer qE;
    public MSPacketSoundEffectBridge Cj;
    public MGlStateManagerFogStateBridge q2;
    public MBlockRayTraceResult D6;
    public MDataComponents q5;
    public MEquippable C3;
    public MBiomeRegistrySwitch qw;
    public MRenderBlocks i;
    public MAxisAlignedBB RQ;
    public MMutableBoundingBox hM;
    public MS08PacketPlayerPosLook q9;
    public MItemRendererBridge o;
    public MEnumHand DX;
    public MGlyphInfo qp;
    public MTileEntity DP;
    public MStyle qi;
    public MSharedMonsterAttributesVariantBridge D7;
    public MClickType qN;
    public MIChunkProvider ho;
    public MRenderSystem f;
    public MGuiSpriteManager h4;
    public MSoundEventRegistryName h9;
    public MStringTextComponent Dh;
    public MItemRenderContext J;
    public MPlayerInteractEvent n;
    public MModelRenderer Rz;
    public MEquipmentSlotSet Ro;
    public MVisGraph Cg;
    public MEntityFX CS;
    public MPacket Cx;
    public MAtomicReferenceArrayBridge H;
    public MEffectRenderer Ru;
    public MGameSettings RM;
    public MKeyBinding hJ;
    public MTextComponentString Dd;
    public MItem CF;
    public MResourceKeyEnchantmentBridge D1;
    public MRenderTypeBufferBridge CU;
    public MNetHandlerPlayClient DY;
    public MEntityRenderer RY;
    public MFoodStats DJ;
    public MMethodSlotZYBridge RV;
    public MRegistryValueBridge l;
    public MRegistry CV;
    public MEntityLivingBase hx;
    public MOpenedChestTypeSentinelBridge CD;
    public MPlayerDiggingAction Ci;
    public MEntityItem Rn;
    public MI18n DB;
    public MBlockPos RP;
    public MTextFormatting Cq;
    public MSPacketMapChunkBulk B;
    public MRenderStateBridge q3;
    public MSetVisibility qy;
    public MFreecamMovementInputBridge Cc;
    public static List<Mapping> RF;
    public MDirectionVector qx;
    public MPointOfView RZ;
    public MCPacketPlayerDigging qA;
    public MCPacketEntityAction Y;
    public MFramebuffer R9;
    public MPlayerSkin hU;
    public MLegacyEntityRenderPreHook qB;
    public MEnumCreatureAttribute hW;
    public MMouseEvent he;
    public MGuiChat Ce;
    public MEntityPlayerMacroBridge Da;
    public MSPacketChunkDataExtracted b;
    public MBlockStateBridge qj;
    public MEntitySelectors CB;
    public MRayTraceContext Rs;
    public MChannel hV;
    public MEnchantments z;
    public MRenderLivingBase CP;
    public MGameSettingsGuiScale Dp;
    public MSPacketHeldItemChange C6;
    public MTextureAtlasSpriteInfoBridge Cz;
    public MEnumCreatureAttributeBridge R0;
    public MSEntityPacket qC;
    public MTextComponentTranslationBridge Dy;
    public MNetworkPlayerInfo RH;
    public MLaunchClassLoader C4;
    public MITextComponent RL;
    public MScreen RT;
    public MEntitySize h2;
    public MNetworkManager Do;
    public MItemArmor DZ;
    public MRayTraceResult C0;
    public MScoreboard Dz;
    public MItem_ToolMaterial Re;
    public MRenderManager CA;
    public MRegistryAccessBridge CT;
    public MEntityRayTraceBridge u;
    public MRenderHelper x;
    public MMinecraft U;
    public MRegistrySimple hD;
    public MItemCameraTransformLeafBridge C;
    public MBytePacketFieldBridge hy;
    public MFluidState RG;
    public MDamageSources h0;
    public MShortPacketFieldBridge F;
    public MEntityPotion hf;
    public MSPacketDestroyEntities C7;
    public MSoundAwareEntityFX R4;
    public MPotionVersionRange Cu;
    public MWorldCollisionConsumerBridge CM;
    public MSPacketDestroyEntitiesArrayBridge Rt;
    public MContainer DD;
    public MGlStateManagerTexGenCoord R_;
    public MRender qe;
    public MNBTTagCompound Dx;
    public MClientChunkProvider Dr;
    public MItemActionResult Di;
    public MClientChatReceivedEvent qP;
    public MLanguageStateBridge S;
    public MAttributeModifier hv;
    public MTextureManager DW;
    public MPotionEffect C8;
    public MSPacketExplosion hQ;
    public MEnumActionResult RD;
    public MCPacketAnimation Q3;
    public MITooltipFlag hO;
    public MEntityPlayer hd;
    public MGuiInventory Q_;
    public MItemSword qF;
    public MChunkSection Rx;
    public MNetworkManager_InboundHandlerTuplePacketListener q;
    public MVoxelShapeBridge Cl;
    public MDefaultVertexFormats DC;
    public MSPacketEntityTeleport qH;
    public MMatrixStackEntry CK;
    public MPositionMoveRotation qT;
    public MTextureAtlasSprite CO;
    public MItemCameraTransformIntermediateBridge T;
    public MTextureObjectHandle DS;
    public MCPacketPlayer Dq;
    public MAbstractBlockState CJ;
    public MEntityArrow qo;
    public MHolder hN;
    public MFoodProperties Dg;
    public MBlock qg;
    public MItemBlock Cw;
    public MGameSettingsGuiScaleValue Dv;
    public MGlyphProvider E;
    public MRenderStateBridgeVariant qX;
    public MResourceLocationConstantsBridge j;
    public MMappedFieldSingletonWrapper CL;
    public MMappedClassSlotNRegistration G;
    public MISelectionContext RR;
    public MVec3d g;
    public MRenderWorldLastEvent Cf;
    public MC03PacketPlayerBridge C_;
    public MBlockPosCarrier hS;
    public MItemStack q8;
    public MMobSpawnerBaseLogic DA;
    public MChunk qD;
    public MEntityFishHook CX;
    public MNetHandlerPlayClientImpl hB;
    public MTileEntityMobSpawner DT;
    public MServerData ht;
    public MRenderStateBuilder C1;
    public MResourceKeyHolder qV;
    public MRayTraceResult_Type q1;
    public MRenderItem DI;
    public MSession hw;
    public MResourceKeyRegistryLookup hl;
    public MTessellator RB;
    public MResourceKey P;
    public MTextComponentTranslation D_;
    public MSPacketChunkData h8;
    public MItemTool M;
    public MSPacketEntityVelocity s;
    public MLanguage D0;
    public MInventoryListBridge DL;
    public MStatusEffectSpriteUploader hk;
    public MItemBlockBridge hb;
    public MEnumParticleTypes Rp;
    public MBiomeRegistryName hq;
    public MGuiScreen h1;
    public MRenderPlayer hn;
    public MVector3f qM;
    public MMappedClassSlotZG hg;
    public MBlockHorizontal a;
    public MBlockLayerOverrideFallbackHook N;
    public MTextComponent RA;
    public MArmorMaterial e;

    public void loadMappings() {
        GuiComponent[] guiComponentArray = ForgeVersion.o();
        if (!Vape.INSTANCE.isNativeAvailable()) {
            this.C4 = new MLaunchClassLoader();
            if (ForgeVersion.MC_1_7_10.L()) {
                this.qv = new MEvent();
                this.qB = new MLegacyEntityRenderPreHook();
            }
        }
        this.U = new MMinecraft();
        this.h1 = new MGuiScreen();
        this.Ce = new MGuiChat();
        this.RT = new MScreen();
        this.hw = new MSession();
        this.RM = new MGameSettings();
        this.hJ = new MKeyBinding();
        this.Rr = new MEntity();
        this.Rn = new MEntityItem();
        this.Dl = new MEntityEnderPearl();
        this.hd = new MEntityPlayer();
        this.CC = new MEntityPlayerSP();
        this.hx = new MEntityLivingBase();
        this.Cy = new MWorld();
        this.ha = new MWorldClient();
        this.Rm = new MBiome();
        this.R7 = new MFontRenderer();
        this.h7 = new MMovementInput();
        this.hj = new MPlayerControllerMP();
        this.g = new MVec3d();
        this.RQ = new MAxisAlignedBB();
        this.C0 = new MRayTraceResult();
        this.RY = new MEntityRenderer();
        this.q1 = new MRayTraceResult_Type();
        this.v = new MInventoryPlayer();
        this.q8 = new MItemStack();
        this.CI = new MItemPotion();
        this.hK = new MGuiContainer();
        this.Q_ = new MGuiInventory();
        this.DD = new MContainer();
        this.qY = new MSlot();
        this.CA = new MRenderManager();
        this.qe = new MRender();
        this.h_ = new MEntityOtherPlayerMP();
        this.qg = new MBlock();
        this.Qv = new MShaderGroup();
        this.Rd = new MBlocks();
        this.hB = new MNetHandlerPlayClientImpl();
        this.Q3 = new MCPacketAnimation();
        this.Y = new MCPacketEntityAction();
        this.RN = new MCPacketChatMessage();
        this.Dq = new MCPacketPlayer();
        this.Cv = new MCPacketPlayer_Rotation();
        this.R5 = new MCPacketPlayer_Position();
        this.qq = new MCPacketPlayer_PositionRotation();
        if (ForgeVersion.MC_1_21_4.d()) {
            this.C_ = new MC03PacketPlayerBridge();
        }
        this.Ck = new MCPacketHeldItemChange();
        this.RE = new MCPacketUseEntityOne();
        this.C6 = new MSPacketHeldItemChange();
        if (ForgeVersion.MC_1_17.v()) {
            this.F = new MShortPacketFieldBridge();
        }
        if (ForgeVersion.MC_1_12_2.d()) {
            this.hp = new MPacketIdFactory();
        }
        this.qU = new MPotion();
        this.C8 = new MPotionEffect();
        this.Do = new MNetworkManager();
        this.CX = new MEntityFishHook();
        this.hC = new MCaughtEntityActionBridge();
        this.Cx = new MPacket();
        this.q = new MNetworkManager_InboundHandlerTuplePacketListener();
        this.DI = new MRenderItem();
        this.Ch = new MGuiChest();
        this.X = new MIInventory();
        this.hr = new MTimer();
        this.Co = new MCPacketUseEntityPacket();
        if (ForgeVersion.MC_26_1.v()) {
            this.Ra = new MCPacketUseEntity();
        }
        this.DJ = new MFoodStats();
        this.Rv = new MIAttributeInstance();
        this.hv = new MAttributeModifier();
        this.qr = new MSharedMonsterAttributes();
        this.CF = new MItem();
        this.RV = new MMethodSlotZYBridge();
        this.Df = new MRenderGlobal();
        this.R9 = new MFramebuffer();
        this.qW = new MTeam();
        this.RL = new MITextComponent();
        this.d = new MGameProfile();
        this.DP = new MTileEntity();
        if (MappedClasses.ZX != null) {
            this.RB = new MTessellator();
        }
        this.DT = new MTileEntityMobSpawner();
        this.DA = new MMobSpawnerBaseLogic();
        this.Ri = new MModelPlayer();
        if (ForgeVersion.MC_1_21_10.v()) {
            this.DZ = new MItemArmor();
        }
        this.Rk = new MEnchantmentHelper();
        this.RC = new MEnchantment();
        this.I = new MNBTTagList();
        this.Dx = new MNBTTagCompound();
        this.qO = new MPacketVelocityBridge();
        this.s = new MSPacketEntityVelocity();
        this.hW = new MEnumCreatureAttribute();
        this.RK = new MDamageSource();
        this.x = new MRenderHelper();
        this.qC = new MSEntityPacket();
        this.DY = new MNetHandlerPlayClient();
        this.CW = new MInputMappings();
        this.Dd = new MTextComponentString();
        this.D_ = new MTextComponentTranslation();
        this.qi = new MStyle();
        this.qD = new MChunk();
        this.ho = new MIChunkProvider();
        this.Ct = new MModelBiped();
        this.Rz = new MModelRenderer();
        this.CP = new MRenderLivingBase();
        this.hn = new MRenderPlayer();
        this.C9 = new MResourceLocation();
        this.hf = new MEntityPotion();
        this.Da = new MEntityPlayerMacroBridge();
        this.qo = new MEntityArrow();
        this.h5 = new MRenderGameOverlayEvent();
        this.hI = new MTileEntityChest();
        this.Ry = new MSPacketPlayerPosLook();
        this.Cs = new MSPacketSoundEffect();
        this.O = new MEnumFacing();
        if (ForgeVersion.c() == ForgeVersion.MC_1_8_9.i() || ForgeVersion.c() == ForgeVersion.MC_1_21_11.i()) {
            this.qt = new MResourceLocationName();
        }
        if (ForgeVersion.c() == ForgeVersion.MC_1_21_11.i()) {
            this.qK = new MResourceLocationKey();
        }
        this.DW = new MTextureManager();
        this.Re = new MItem_ToolMaterial();
        this.e = new MArmorMaterial();
        this.Db = new MGuiContainerCreativeSlot();
        this.ql = new MTitledScreen();
        this.D4 = new MTileEntityEnderChest();
        this.hO = new MITooltipFlag();
        this.ht = new MServerData();
        this.D2 = new MGlStateManager_FogState();
        this.Dj = new MBlockBed();
        this.C5 = new MPlaySoundAtEntityEvent();
        this.m = new MMappedClassSlotFp();
        this.Dk = new MAbstractClientPlayerBridge();
        this.Dz = new MScoreboard();
        this.qL = new MScoreObjective();
        this.Cm = new MScore();
        this.Rh = new MScorePlayerTeam();
        this.DB = new MI18n();
        this.k = new MGL11();
        this.RW = new MGL20();
        this.D0 = new MLanguage();
        this.W = new MEntityLiving();
        this.RO = new MSPacketEntityStatus();
        this.DF = new MSPacketAnimation();
        this.qR = new MSPacketEntity();
        this.qH = new MSPacketEntityTeleport();
        this.Rt = new MSPacketDestroyEntitiesArrayBridge();
        this.D3 = new MCPacketPlayerBlockPlacement();
        this.qP = new MClientChatReceivedEvent();
        this.hy = new MBytePacketFieldBridge();
        this.hG = new MTextureObject();
        this.hb = new MItemBlockBridge();
        this.B = new MSPacketMapChunkBulk();
        if (GuiRenderPrimitives.V()) {
            this.Rf = new MUtil();
        }
        if (MappedClasses.ZC != null) {
            this.hs = new MGlStateManagerTexGenState();
        }
        if (MappedClasses.lO != null) {
            this.Cf = new MRenderWorldLastEvent();
            Vape.renderReady = true;
        }
        if (MappedClasses.Ym != null) {
            this.Dv = new MGameSettingsGuiScaleValue();
        }
        if (ForgeVersion.MC_1_7_10.Y()) {
            this.Cg = new MVisGraph();
            this.qy = new MSetVisibility();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.hE = new MBlockModelRenderer();
            }
            this.n = new MPlayerInteractEvent();
            this.hP = new MGuiPlayerTabOverlay();
            this.CN = new MSPacketBlockChange();
            this.Dn = new MVec3I();
            this.RP = new MBlockPos();
            this.DE = new MIBlockState();
            this.Dt = new MGlStateManager();
            this.DQ = new MC0BPacketEntityAction_Action();
            this.CG = new MPlayerInfo();
            this.qZ = new MWorldRenderer();
            this.DC = new MDefaultVertexFormats();
            this.hg = new MMappedClassSlotZG();
            this.Dm = new MIWorldNameable();
            this.Rc = new MPlayerModel();
            this.Rp = new MEnumParticleTypes();
            this.Cs = new MSPacketSoundEffect();
            this.R4 = new MSoundAwareEntityFX();
            this.Rp = new MEnumParticleTypes();
            this.S = new MLanguageStateBridge();
            this.a = new MBlockHorizontal();
            this.hH = new MGlStateManager_TextureState();
            this.he = new MMouseEvent();
            this.qG = new MGlStateManager_BlendState();
            if (ForgeVersion.c() <= ForgeVersion.MC_1_8_9.i()) {
                this.qA = new MCPacketPlayerDigging();
            }
            this.Rx = new MChunkSection();
        } else {
            this.i = new MRenderBlocks();
            this.q_ = new MEntityClientPlayerMP();
        }
        if (ForgeVersion.MC_1_8_9.L()) {
            this.R1 = new MPlayerEvent_NameFormat();
            this.qE = new MItemRenderer();
            this.Ci = new MPlayerDiggingAction();
            this.o = new MItemRendererBridge();
            this.h8 = new MSPacketChunkData();
            this.b = new MSPacketChunkDataExtracted();
            this.Rg = new MSPacketMapChunkBulkBridge();
            this.Dr = new MClientChunkProvider();
            this.Dw = new MWorldInfo();
        }
        if (ForgeVersion.MC_1_12_2.d()) {
            this.q6 = new MMoverType();
            this.DX = new MEnumHand();
            this.Cq = new MTextFormatting();
            this.qN = new MClickType();
            this.CY = new MEntityEquipmentSlot();
            this.RD = new MEnumActionResult();
            this.DR = new MNonNullList();
            this.CB = new MEntitySelectors();
        } else {
            this.Ru = new MEffectRenderer();
        }
        if (MappedClasses.Yb != null) {
            this.Cd = new MItemAttributeModifiers();
            this.Rw = new MEmptyItemAttributeModifiers();
            this.hY = new MLists();
            this.qm = new MOrdering();
        }
        this.hi = new MActiveRenderInfo();
        if (ForgeVersion.MC_1_16_5.d()) {
            this.RX = new MTrajectoriesItemBridge();
            this.RR = new MISelectionContext();
            this.V = new MEntityRendererFogDensityHook();
            this.hz = new MTickEvent_Phase();
            this.qI = new MMouseHelper();
            this.RZ = new MPointOfView();
            this.hm = new MInputMappingsInput();
            this.h2 = new MEntitySize();
            this.Rj = new MMLGBlockWrapper();
            if (ForgeVersion.MC_1_20_6.v()) {
                this.hq = new MBiomeRegistryName();
            }
            this.p = new MDirectionAxis();
            this.qx = new MDirectionVector();
            this.hu = new MBlockStateWorldBridge();
            this.hF = new MLightTexture();
            this.y = new MBlockReaderBridge();
            this.RA = new MTextComponent();
            this.Dh = new MStringTextComponent();
            this.RJ = new MMutableTextComponent();
            this.Rb = new MStatusEffect();
            this.Cb = new MSoundEvent();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.hk = new MStatusEffectSpriteUploader();
            }
            this.R6 = new MTextureAtlasSpriteInfo();
            this.CO = new MTextureAtlasSprite();
            this.qn = new MMatrixStack();
            this.qJ = new MMatrix4f();
            this.CK = new MMatrixStackEntry();
            this.qQ = new MAbstractGui();
            this.qM = new MVector3f();
            this.Rs = new MRayTraceContext();
            this.R3 = new MRayTraceContext_BlockMode();
            this.DG = new MRayTraceContext_FluidMode();
            this.Cr = new MVoxelShape();
            this.CQ = new MAbstractBlockProperties();
            this.CJ = new MAbstractBlockState();
            this.qf = new MQuaternion();
            this.c = new MRenderTypeBuffer();
            this.qc = new MRegistryNamespaced();
            this.CE = new MInputMappingsBridge();
            this.hM = new MMutableBoundingBox();
            this.qS = new MEntityRayTraceResult();
            this.Q = new MDirection();
            this.D6 = new MBlockRayTraceResult();
            this.f = new MRenderSystem();
            this.Ro = new MEquipmentSlotSet();
            this.q0 = new MWorldClientBridge();
        } else {
            this.qw = new MBiomeRegistrySwitch();
            this.t = new MEnchantmentModifierDamage();
            if (ForgeVersion.MC_1_12_2.d()) {
                this.CD = new MOpenedChestTypeSentinelBridge();
            }
            if (ForgeVersion.MC_1_7_10.Y()) {
                this.hA = new MEnumWorldBlockLayer();
            }
            this.RG = new MFluidState();
        }
        this.hD = new MRegistrySimple();
        this.N = new MBlockLayerOverrideFallbackHook();
        if (ForgeVersion.MC_1_17.d()) {
            this.D7 = new MSharedMonsterAttributesVariantBridge();
            this.h = new MEntityRemovalReason();
            if (ForgeVersion.MC_26_1.v()) {
                this.qz = new MCPacketUseEntityAction();
                this.h6 = new MCPacketUseEntityActionPacket();
            }
            this.CM = new MWorldCollisionConsumerBridge();
            this.D9 = new MMinecraftBridge();
            this.hS = new MBlockPosCarrier();
            this.Cw = new MItemBlock();
            this.H = new MAtomicReferenceArrayBridge();
            this.A = new MRenderItemContext();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.hV = new MChannel();
            }
            this.Cl = new MVoxelShapeBridge();
        }
        if (ForgeVersion.MC_1_20_6.d()) {
            if (ForgeVersion.MC_1_21_10.v()) {
                this.D = new MWorldRendererBuilder();
            }
            this.DM = new MGameSettingsValue();
            this.hQ = new MSPacketExplosion();
            this.Dp = new MGameSettingsGuiScale();
            this.hU = new MPlayerSkin();
            this.q7 = new MBuiltInRegistries();
            this.CV = new MRegistry();
            this.hh = new MEntityEquipmentSlotHolder();
            this.q5 = new MDataComponents();
            this.hN = new MHolder();
            this.h3 = new MSharedMonsterAttributesBridge();
            this.K = new MBiomeProviderBridge();
            this.Rq = new MMatrix4fTransformVariantBridge();
            this.h9 = new MSoundEventRegistryName();
            this.P = new MResourceKey();
            this.R8 = new MTickEventPhase();
            if (ForgeVersion.MC_1_21_6.v()) {
                this.hR = new MEnumHandBridge();
            }
            this.RS = new MEmptyDataComponentMap();
            this.Cu = new MPotionVersionRange();
            this.Dc = new MVertexFormatElement();
            this.CR = new MKeyboardHandler();
        } else {
            this.Cn = new MMaterial();
            this.R0 = new MEnumCreatureAttributeBridge();
        }
        if (ForgeVersion.MC_1_21_0.d()) {
            this.RU = new MDeltaTracker();
            if (ForgeVersion.MC_1_20_6.v()) {
                this.C1 = new MRenderStateBuilder();
            }
            this.z = new MEnchantments();
        }
        if (ForgeVersion.MC_1_21_11.d()) {
            this.u = new MEntityRayTraceBridge();
        }
        if (ForgeVersion.MC_1_21_4.d()) {
            this.qT = new MPositionMoveRotation();
            this.Cc = new MFreecamMovementInputBridge();
            this.Rl = new MItems();
            this.q3 = new MRenderStateBridge();
            this.qk = new MDataComponentMap();
            this.D5 = new MDirectionBridge();
            this.r = new MItemAttributeModifiersComponent();
            this.DN = new MItemAttributeModifiersComponent$Entry();
            this.C3 = new MEquippable();
            this.qV = new MResourceKeyHolder();
            this.qu = new MItemCameraTransformType();
            this.hc = new MItemCameraTransformBaseBridge();
            this.T = new MItemCameraTransformIntermediateBridge();
            this.C = new MItemCameraTransformLeafBridge();
            this.L = new MChestTypeHolder();
            this.G = new MMappedClassSlotNRegistration();
            this.C7 = new MSPacketDestroyEntities();
            this.h0 = new MDamageSources();
            this.hT = new MFoods();
            this.Dg = new MFoodProperties();
            this.DV = new MBlockReader();
            this.qa = new MChestType();
            this.qh = new MITooltipFlagBridge();
            this.D1 = new MResourceKeyEnchantmentBridge();
            this.qs = new MRegistryAccess();
            this.q9 = new MS08PacketPlayerPosLook();
            this.CS = new MEntityFX();
            this.RH = new MNetworkPlayerInfo();
        }
        if (ForgeVersion.MC_1_21_6.d()) {
            this.RI = new MPlayerInput();
            this.Ca = new MRenderBufferBridge();
            if (ForgeVersion.MC_26_1.d()) {
                this.Ds = new MBlockStateContainerBridge();
            }
            this.hX = new MRenderBatchFlushTarget();
            this.DL = new MInventoryListBridge();
            this.CL = new MMappedFieldSingletonWrapper();
            this.DS = new MTextureObjectHandle();
            this.h4 = new MGuiSpriteManager();
            this.D8 = new MMatrix4fHandle();
            this.R = new MGlStateManagerFogStateObject();
            this.q2 = new MGlStateManagerFogStateBridge();
            this.DK = new MStringTextComponentBridge();
            this.Dy = new MTextComponentTranslationBridge();
            this.DU = new MMainWindow();
        } else {
            this.M = new MItemTool();
            this.qF = new MItemSword();
        }
        if (ForgeVersion.MC_1_21_10.d()) {
            this.CZ = new MModelManager();
            this.j = new MResourceLocationConstantsBridge();
            this.w = new MFreecamPlayerBridge();
            this.Cz = new MTextureAtlasSpriteInfoBridge();
            this.Du = new MAbstractClientPlayer();
            this.hL = new MTextureManagerHandle();
            this.hZ = new MFontGlyphInfo();
            this.qj = new MBlockStateBridge();
            this.De = new MFontGlyph();
            this.qp = new MGlyphInfo();
            this.Z = new MFontSet();
            this.qb = new MFontManager();
            this.E = new MGlyphProvider();
            this.CU = new MRenderTypeBufferBridge();
            this.C2 = new MResourceManager();
        }
        this.CH = new MEnderPearlProjectileBridge();
        if (ForgeVersion.MC_1_20_6.d()) {
            this.qd = new MChatMessageRenderTarget();
            this.Cp = new MTextComponentBaseBridge();
            this.q4 = new MEnchantmentHelperBridge();
            this.R2 = new MResourceKeyRegistryLookupStreamBridge();
            this.CT = new MRegistryAccessBridge();
            this.l = new MRegistryValueBridge();
            this.Cj = new MSPacketSoundEffectBridge();
            this.qX = new MRenderStateBridgeVariant();
            this.DO = new MRegistryLookup();
            this.hl = new MResourceKeyRegistryLookup();
        }
        if (ForgeVersion.MC_1_21_4.d()) {
            this.R_ = new MGlStateManagerTexGenCoord();
            this.J = new MItemRenderContext();
            this.Di = new MItemActionResult();
        }
    }

    public static void j(int n) {
        DH = n;
    }

    static {
        RF = new ArrayList<Mapping>();
        Mapper.j(34);
    }

    public static int D() {
        int n = Mapper.u();
        return 0;
    }

    private static ObfuscatedRuntimeException a(ObfuscatedRuntimeException obfuscatedRuntimeException) {
        return obfuscatedRuntimeException;
    }

    public static int u() {
        return DH;
    }
}

